name: upload bot app with go-build
on:
  push:
    branches:
      - main
defaults:
  run:
    working-directory: "bot"
jobs:
  upload-bot-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_CRED_BASE64 }}
          export_default_credentials: true
      - name: build
        id: build
        run: GOOS=linux GOARCH=amd64 go build
      - name: upload to gcs
        id: upload-gcs
        run: gsutil cp bot gs://minecraft-abekoh-bot/
