name: upload scripts to Google Cloud Storage
on:
  push:
    branches:
      - main
jobs:
  upload-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_CRED_BASE64 }}
          export_default_credentials: true
      - name: upload to gcs
        id: upload-gcs
        run: gsutil cp scripts/* gs://minecraft-abekoh-scripts/
